/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body className={inter.className}>
				<div className="flex dark:text-zinc-100 dark:bg-zinc-800">
					<Sidebar />
					<div className="flex flex-col w-full">
						<div className="flex items-center justify-center h-full">
							<div className="bg-zinc-50 dark:bg-zinc-700 shadow-sm rounded-xl p-10">
								<div>{children}</div>
							</div>
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
