export interface Nfe {
    idnfe: number,
    cdv: string,
    cmunfg: string,
    cnf: string,
    cuf: string,
    dhemi: string,
    dhsaient: string,
    finnfe: string,
    iddest: string,
    indfinal: string,
    indintermed: string,
    indpres: string,
    modnfe: string,
    nnf: string,
    natop: string,
    procemi: string,
    serie: string,
    tpamb: string,
    tpemis: string,
    tpimp: string,
    tpnf: string,
    verproc: string,
    nftotal: string,
    nfe_idemit: number,
    nfe_iddest: number,
}
