export interface Nfe {
    nfeidnfe: number,
    c_dv: string,
    c_mun_fg: string,
    c_nf: string,
    c_uf: string,
    dh_emi: string,
    dh_sai_ent: string,
    fin_nfe: string,
    id_dest: string,
    ind_final: string,
    ind_intermed: string,
    ind_pres: string,
    mod_nfe: string,
    n_nf: string,
    nat_op: string,
    proc_emi: string,
    serie: string,
    tp_amb: string,
    tp_emis: string,
    tp_imp: string,
    tp_nf: string,
    ver_proc: string,
    nf_total: string,
    emit: number,
    dest: number,
}
